### ISSUE TITLE
[Results] No se ejecuta experimento con aljarafe y asomadilla

### ISSUE THREAD

**Issue by gualbe** [gualbe/weka-time-series-studio#2]
Como datasets, agregamos aljarafe.arff y asomadilla.arff:

[aljarafe_asomadilla.zip](https://github.com/gualbe/weka-time-series-studio/files/8687000/aljarafe_asomadilla.zip)

Como target indicamos O3-AT_IN con 6 horizontes.

Formato de fecha/hora a: "dd/MM/yyyy HH:mm:ss"

En features agregamos 12 lagged para todas las variables (O3, PM10, NO2, TMP y VV).

En Algorithms añadimos sólo IBk.

En Validation, indicamos Relative: 70%.

En Training increments no me deja indicar el número de instancias (me aparece deshabilitado):

![Captura de Pantalla 2022-05-13 a las 14 27 23](https://user-images.githubusercontent.com/13599751/168282887-674282cf-18b3-4a56-8db7-76e3233efeb8.png)

Al ejecutar con el botón Run, se queda sin hacer nada:

![Captura de Pantalla 2022-05-13 a las 14 28 01](https://user-images.githubusercontent.com/13599751/168282985-56451552-3ddc-45e1-b53a-c1a2909a5794.png)

**Comment by mamofu** [comment]
- Se ha arreglado el problema de training increment deshabilitado
- Se ha arreglado el problema de que el experimento no ejecutaba. Ahora si ejecuta
